name: push site
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # 添加以下步骤来更新 Node.js 版本
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install -g mkdocs-material # 安装 mkdocs-material
      - run: mkdocs gh-deploy --force
